eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
server:
  port: 9095

spring:
  application:
    name: portal-feign
  zipkin:
    base-url: http://localhost:8961

feign:
  hystrix:
    enabled: true

