
server:
  port: 9098
spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:8961
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
    id-service:
      path: /id/**
      serviceId: id-service

  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000


ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000


hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000

swagger:
  title: 原子服务层接口API
  description: 显示原子服务层接口API文档，方便用户测试
  version: V1.0
  basePackage: com.service.zuul
  show: true

feign:
  hystrix:
    enabled: true